# Kubernetes ResourceQuota and LimitRange for Nginx Deployments
# This configuration provides resource governance for nginx applications
# Includes namespace setup, LimitRange defaults, and ResourceQuota limits

---
# 1. Create Namespace for Nginx Deployments
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-apps
  labels:
    environment: production
    managed-by: devops-team

---
# 2. LimitRange - Sets default requests/limits and constraints per Pod/Container
# Applied FIRST before ResourceQuota to ensure all pods have resource specs
apiVersion: v1
kind: LimitRange
metadata:
  name: nginx-limit-range
  namespace: nginx-apps
  annotations:
    description: "Default resource limits for nginx containers and pods"
    created-date: "2025-11-09"
spec:
  limits:
  # Container-level constraints
  - type: Container
    max:
      cpu: "1"                    # Max 1 CPU core per container
      memory: "512Mi"             # Max 512MB per container
    min:
      cpu: "100m"                 # Min 100 millicores per container
      memory: "64Mi"              # Min 64MB per container
    default:                       # Auto-applied limits if not specified
      cpu: "500m"
      memory: "256Mi"
    defaultRequest:               # Auto-applied requests if not specified
      cpu: "100m"
      memory: "128Mi"
  
  # Pod-level constraints (sum of all containers)
  - type: Pod
    max:
      cpu: "2"                    # Max 2 CPU cores per pod
      memory: "1Gi"               # Max 1GB per pod
    min:
      cpu: "200m"                 # Min 200 millicores per pod
      memory: "128Mi"             # Min 128MB per pod

---
# 3. ResourceQuota - Enforces namespace-level aggregate limits
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nginx-quota
  namespace: nginx-apps
  annotations:
    description: "Resource quota for nginx deployments"
    business-unit: "Platform"
    cost-center: "INFRA-001"
    max-pods-allowed: "50"
    created-date: "2025-11-09"
    last-reviewed: "2025-11-09"
    next-review: "2026-02-09"
spec:
  hard:
    # Compute Resources - CPU
    requests.cpu: "10"            # Total CPU requested across all pods: 10 cores
    limits.cpu: "20"              # Total CPU limits across all pods: 20 cores
    
    # Compute Resources - Memory
    requests.memory: "20Gi"       # Total memory requested: 20GB
    limits.memory: "40Gi"         # Total memory limits: 40GB
    
    # Object Count Limits
    pods: "50"                    # Maximum 50 pods total in namespace
    services: "10"                # Maximum 10 services (ClusterIP, NodePort, LoadBalancer)
    deployments.apps: "25"        # Maximum 25 deployments
    replicasets.apps: "25"        # Maximum 25 replica sets
    statefulsets.apps: "5"        # Maximum 5 stateful sets
    configmaps: "50"              # Maximum 50 config maps
    secrets: "30"                 # Maximum 30 secrets
    persistentvolumeclaims: "10"  # Maximum 10 PVCs
    
    # Storage
    requests.storage: "100Gi"     # Total storage allocation across all PVCs
    
    # Pod disruption budgets
    poddisruptionbudgets.policy: "5"

---
# 4. Example Nginx Deployment (complies with above quotas)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
  namespace: nginx-apps
  labels:
    app: nginx
    tier: frontend
    environment: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        environment: production
    spec:
      # Resource requests and limits (required by ResourceQuota)
      containers:
      - name: nginx
        image: nginx:1.24-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: metrics
          containerPort: 9113
          protocol: TCP
        
        # Resource specifications - REQUIRED by ResourceQuota
        resources:
          requests:
            cpu: "100m"           # Guaranteed minimum CPU
            memory: "128Mi"       # Guaranteed minimum memory
          limits:
            cpu: "500m"           # Maximum CPU cap
            memory: "256Mi"       # Maximum memory cap
        
        # Health checks ensure only healthy pods receive traffic
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        
        # Volume mounts
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: cache
          mountPath: /var/cache/nginx
      
      # Pod-level settings
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      
      volumes:
      - name: config
        configMap:
          name: nginx-config
      - name: cache
        emptyDir: {}

---
# 5. Service to expose Nginx Deployment (counted in quota)
apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend-service
  namespace: nginx-apps
  labels:
    app: nginx
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: nginx
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http

---
# 6. ConfigMap for Nginx Configuration (counted in quota)
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-apps
data:
  default.conf: |
    upstream backend {
      least_conn;
      server backend-service:8080;
    }
    
    server {
      listen 80;
      server_name _;
      
      client_max_body_size 100M;
      
      location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
      }
      
      location /health {
        access_log off;
        return 200 "healthy\n";
      }
    }

---
# 7. HorizontalPodAutoscaler - Works within ResourceQuota limits
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-frontend-hpa
  namespace: nginx-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-frontend
  minReplicas: 3
  maxReplicas: 10              # Limited by pod quota (50 pods max in namespace)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30

---
# 8. NetworkPolicy - Restricts traffic to Nginx pods (security layer)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-network-policy
  namespace: nginx-apps
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - podSelector:
        matchLabels:
          role: frontend
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53    # DNS
    - protocol: UDP
      port: 53    # DNS
    - protocol: TCP
      port: 8080  # Backend service
    - protocol: TCP
      port: 443   # HTTPS

---
# 9. PodDisruptionBudget - Ensures availability during disruptions (respects quota)
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb
  namespace: nginx-apps
spec:
  minAvailable: 2             # Always keep at least 2 nginx pods running
  selector:
    matchLabels:
      app: nginx
      tier: frontend

---
# NOTES AND GUIDELINES
# ===================
# 
# 1. QUOTA ALLOCATION BREAKDOWN:
#    - CPU Requests: 10 cores
#      * 3 replicas × 100m (min) = 300m used
#      * HPA can scale to 10 pods × 100m = 1000m (10% of quota)
#    
#    - Memory Requests: 20Gi
#      * 3 replicas × 128Mi = 384Mi used
#      * 10 replicas × 128Mi = 1.28Gi (6.4% of quota)
#    
#    - Quotas sized for:
#      * Base nginx deployment: 3 replicas
#      * HPA scaling to ~10 pods
#      * Multiple nginx deployments/services
#      * Configuration and secrets storage
#      * Future growth (20-30% buffer)
#
# 2. MONITORING QUOTA USAGE:
#    kubectl describe resourcequota nginx-quota -n nginx-apps
#    kubectl top pods -n nginx-apps
#    kubectl get resourcequota -n nginx-apps -o wide
#
# 3. QUOTA ENFORCEMENT RULES:
#    ✓ All pods MUST have resource requests/limits
#    ✓ LimitRange provides defaults if not specified
#    ✓ Pod creation fails if quota would be exceeded
#    ✓ Quota is checked at creation time only
#    ✓ Quota reconciles every 5 minutes
#
# 4. SCALING BEHAVIOR:
#    ✓ HPA respects pod quota (maxReplicas: 10)
#    ✓ HPA respects memory/CPU quotas
#    ✓ Scaling fails if quota limit reached
#    ✓ Monitor quota utilization when scaling
#
# 5. TROUBLESHOOTING:
#    - Pod rejected: Check quota with describe command
#    - Quota shows used but no pods visible: Wait 5 min for reconciliation
#    - HPA not scaling: Check quota limits and actual resource usage
#
# 6. APPLYING THIS CONFIGURATION:
#    kubectl apply -f nginx-resourcequota.yaml
#
# 7. ADJUSTING QUOTAS:
#    - Review quarterly based on actual usage
#    - Monitor with: kubectl top pods -n nginx-apps --containers
#    - Edit quota: kubectl edit resourcequota nginx-quota -n nginx-apps
#    - Keep 20-30% headroom for spikes and growth